# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Test' do
end

target 'TestTests' do
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'XCAsyncTestCase', :git => 'https://github.com/fengyang0329/XCAsyncTestCase.git'
pod 'UIPageTest', :git => 'https://github.com/fengyang0329/gitskills.git'

end

